version: '3'

services:
  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    network_mode: host
    volumes:
      - '/volume1/docker/openspeedtest/data:/data'
    restart: unless-stopped
