version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'change this when pasting =)'
      WEB_PORT: '8081'
    volumes:
      - '/volume2/docker/Pihole/pihole:/etc/pihole'
      - '/volume2/docker/Pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
